---
abstract: 'Client code for querying multiple DNSBLs'
author:
  - 'David Skoll <dfs@roaringpenguin.com>,'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0.82
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DNSBL-Client
no_index:
  directory:
    - inc
    - t
requires:
  IO::Socket: 0
  Net::DNS::Resolver: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.204
